title: Yeftha Joshua Ezekiel
logo: /assets/img/mugshot.jpeg
description: "Hello, my name is Yeftha Joshua Ezekiel, and I am passionate about the field of AI."
theme: jekyll-theme-minimal
markdown: GFM
