title: Yeftha Joshua Ezekiel
logo: /assets/img/mugshot.jpeg
description: "Hello, my name is Yeftha Joshua Ezekiel, and I am passionate about the field of AI. I have experience in various machine learning projects and aspire to become a data scientist/MLE."
show_downloads: true
theme: jekyll-theme-minimal
markdown: GFM
