title: Yeftha Joshua Ezekiel
logo: <img src="assets/img/mugshot.jpeg" width="200"/>
description: Hello, my name is Yeftha Joshua Ezekiel, and I am passionate about the field of AI. I have a strong background, specifically in the fields of machine learning and data. As part of the Computer & Network Laboratory and a Bangkit Academy alumnus, I have been trained to enhance my hard skills and soft skills in leadership, effective communication, and teamwork. I have experience in various machine learning projects and aspire to become a data scientist/MLE.
show_downloads: true
theme: jekyll-theme-minimal
markdown: GFM
